### PR TITLE
split up huge ias-verify file

### LINKED ISSUE #35: Incorrect handling of a finished iteration in verify_ias_report causes panic
# Summary

The extrinsic function `verify_ias_report` in `pallet-teerex/ias-verify/src/lib.rs` does not check the return value of the iterator when it's yields `None` and causes nodes to panic. As the panic condition can be triggered by an attacker via an `register_enclave` extrinsic call, it could provide attackers a low cost opportunity to perform a DoS attack against the whole chain. 

# Issue

In `pallet-teerex/ias-verify/src/lib.rs`, the extrinsic `register_enclave` calls into `verify_ias_report` function in `pallet-teerex/ias-verify/src/lib.rs` which does not check the return value of the iterator after calling `iter.next()` and in a case where the iteration is finished, `iter.next()` returns `None`, causing the `unwrap()` call to panic.

```rust
pub fn verify_ias_report(cert_der: &[u8]) -> Result<SgxReport, &'static str> {
[...]
    // Extract each field
    let mut iter = payload.split(|x| *x == 0x7C);
    let attn_report_raw = iter.next().unwrap();
    let sig_raw = iter.next().unwrap();
    let sig = match base64::decode(&sig_raw) {
```

The below call can be used to reproduce the unwrap None issue:

```rust
Call::SubstrateeRegistry(register_enclave([224, 224, 224, 224, 224, 224, 224, 224, 235, 2, 0, 1, 5, 40, 0, 8, 255, 6, 8, 42, 134, 72, 206, 61, 3, 1, 7, 0, 2, 183, 64, 48, 48, 0, 1, 10, 23, 3, 6, 9, 96, 134, 72, 1, 134, 248, 66, 1, 13, 0, 0, 0, 13, 1, 14, 177], []))
```

# Risk

Since this can be triggered by a call to an extrinsic an attacker could cause a validator node to crash by submitting a specially crafted extrinsic and cause them miss their block authoring slot. This could lead **to a denial-of-service of the whole chain** with only very low cost requirements for the attacker.

# Mitigation

We suggest to amend the implementation of `verify_ias_report` by adding the logic of checking the value of `iter.next()` to correctly handle the case when it returns `None`.

### PR DESCRIPTION
**Pull request by clangenb**
While working on #39, I did some cleanup on the go.

Todo:

- [x]  Merge #33 first.
- [x] rebase on master
- [x] retarget this PR to master

### CODE REVIEW

File: ias-verify/src/ephemeral_key.rs [hunk 1]
```diff
@@ -0,0 +1,32 @@
+use crate::utils::{length_from_raw_data, safe_indexing};
```
Comment (clangenb) [inline ias-verify/src/ephemeral_key.rs:1]: This code was in `verify_ias_report` but the key was not checked against anything. I extracted it to here, but I do not call it anymore because I don't think extracting the key verifies something valuable.

File: ias-verify/src/lib.rs [hunk 2]
```diff
@@ -155,137 +156,31 @@ pub static IAS_SERVER_ROOTS: webpki::TLSServerTrustAnchors = webpki::TLSServerTr
 
 ]);
 
-// prevents panics in case of index out of bounds
```
Comment (clangenb) [inline ias-verify/src/lib.rs:158]: Moved as is to utils

File: ias-verify/src/lib.rs [hunk 3]
```diff
@@ -377,132 +272,49 @@ fn parse_report(report_raw: &[u8]) -> Result<SgxReport, &'static str> {
     }
 }
 
-#[cfg(test)]
```
Comment (clangenb) [inline ias-verify/src/lib.rs:380]: moved to `tests.rs` as is

File: ias-verify/src/netscape_comment.rs [hunk 4]
```diff
@@ -0,0 +1,53 @@
...
+        println!("netscape");
+        // Obtain Netscape Comment length
+        let len = length_from_raw_data(cert_der, &mut offset)?;
+        // Obtain Netscape Comment
+        offset += 1;
+        let netscape_raw = safe_indexing(cert_der, offset, offset + len)?
+            .split(|x| *x == 0x7C)
+            .collect::<Vec<&[u8]>>();
+
+        ensure!(netscape_raw.len() == 3, "Invalid netscape payload");
```
Comment (clangenb) [inline ias-verify/src/netscape_comment.rs:40]: This is actually the fix for #35. Before, we iterated here three times and unwrapped without checking it `next()` yielded `Some`

File: ias-verify/src/netscape_comment.rs [hunk 5]
```diff
@@ -0,0 +1,53 @@
...
+}
+
+pub const NS_CMT_OID: &[u8; 11] = &[
+    0x06, 0x09, 0x60, 0x86, 0x48, 0x01, 0x86, 0xF8, 0x42, 0x01, 0x0D,
+];
+
+impl<'a> TryFrom<CertDer<'a>> for NetscapeComment<'a> {
+    type Error = &'static str;
+
+    fn try_from(value: CertDer<'a>) -> Result<Self, Self::Error> {
```
Comment (clangenb) [inline ias-verify/src/netscape_comment.rs:19]: Apart from the fix mentioned below, this code is copied from the `verify_ias_report` function

File: ias-verify/src/tests.rs [hunk 6]
```diff
@@ -0,0 +1,145 @@
...
+    // For context, see: https://github.com/integritee-network/pallet-teerex/issues/35
+
+    let report: [u8; 56] = [
+        224, 224, 224, 224, 224, 224, 224, 224, 235, 2, 0, 1, 5, 40, 0, 8, 255, 6, 8, 42, 134, 72,
+        206, 61, 3, 1, 7, 0, 2, 183, 64, 48, 48, 0, 1, 10, 23, 3, 6, 9, 96, 134, 72, 1, 134, 248,
+        66, 1, 13, 0, 0, 0, 13, 1, 14, 177,
+    ];
+
+    assert_err!(verify_ias_report(&report), "Invalid netscape payload");
+}
```
Comment (clangenb) [inline ias-verify/src/tests.rs:145]: Test the fix.

File: ias-verify/src/utils.rs [hunk 7]
```diff
@@ -0,0 +1,27 @@
+// prevents panics in case of index out of bounds
```
Comment (clangenb) [inline ias-verify/src/utils.rs:1]: Copied from lib.rs

File: ias-verify/src/netscape_comment.rs (hunk 5 above)
Comment (mullefel) [reply ias-verify/src/netscape_comment.rs:19]: This seems to be more or less duplicated in the worker. How much work would it be to extract this code and share it across the pallet and the worker? Do we already have an existing library that can act as such a vessel?

File: ias-verify/src/tests.rs (hunk 6 above)
Comment (mullefel) [reply ias-verify/src/tests.rs:145]: nice 🚀

File: ias-verify/src/netscape_comment.rs (hunk 5 above)
Comment (clangenb) [reply ias-verify/src/netscape_comment.rs:19]: Yes, this is almost an exact duplicate. We have not discussed yet, how we want to share code. We should talk about that in our next call.

File: ias-verify/src/tests.rs (hunk 6 above)
Comment (clangenb) [reply ias-verify/src/tests.rs:145]: I took this one from #35.

If I needed to generate one, I would print  a report by the enclave and copy-paste it here.

File: ias-verify/src/netscape_comment.rs (hunk 5 above)
Comment (mullefel) [reply ias-verify/src/netscape_comment.rs:19]: do we have an issue for this? otherwise we need to create one..

**Review by mullefel — APPROVED** [review]
looks good to me, good job reducing the amount of code in these (way too) large source files

File: ias-verify/src/netscape_comment.rs (hunk 5 above)
Comment (clangenb) [reply ias-verify/src/netscape_comment.rs:19]: Done: https://github.com/integritee-network/worker/issues/323

**Comment by brenzi** [comment]
As the original issue originated from a security review, I would've preferred fixing the issue and refactoring separately so that we can easily point to the fix as a separate commit. No need to change that now IMO, but security fixes are not a good occasion to do cosmetics

**Comment by clangenb** [comment]
> 
> 
> As the original issue originated from a security review, I would've preferred fixing the issue and refactoring separately so that we can easily point to the fix as a separate commit. No need to change that now IMO, but security fixes are not a good occasion to do cosmetics

You are absolutely right. I extracted the relevant code to another file.
